{
 "title": "Simple Flink Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "deploymentId", "query": "label_values(deploymentId)" }
  ]
 },
 "panels": [
  { "title": "General Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "flink_jobmanager_job_uptime{deploymentId=\"$deploymentId\"}",
     "legendFormat": "Job {{job_id}}"
    }
   ]
  },
  {
   "title": "Job Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(flink_jobmanager_job_numRestarts{deploymentId=\"$deploymentId\"}[$__range]))",
     "legendFormat": "Job {{job_id}}"
    }
   ]
  },
  {
   "title": "Last Checkpoint Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointSize{deploymentId=\"$deploymentId\"}",
     "legendFormat": "Job {{job_id}}"
    }
   ]
  },
  {
   "title": "Last Checkpoint Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointDuration{deploymentId=\"$deploymentId\"}",
     "legendFormat": "Job {{job_id}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Records/s" }
   ],
   "targets": [
    {
     "expr": "sum by (task_name) (flink_taskmanager_job_task_numRecordsOutPerSecond{deploymentId=\"$deploymentId\"})",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Task Managers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers",
     "legendFormat": "TaskManagers"
    }
   ]
  },
  { "title": "Checkpointing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Failed Checkpoints",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(flink_jobmanager_job_numberOfFailedCheckpoints{deploymentId=\"$deploymentId\"}[$__range]))",
     "legendFormat": "Job {{job_id}}"
    }
   ]
  },
  {
   "title": "Successfull Checkpoints",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(flink_jobmanager_job_numberOfCompletedCheckpoints{deploymentId=\"$deploymentId\"}[$__range]))",
     "legendFormat": "Job {{job_id}}"
    }
   ]
  },
  {
   "title": "Last Checkpoint Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointSize{deploymentId=\"$deploymentId\"}"
    }
   ]
  },
  {
   "title": "Last Checkpoint Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointDuration{deploymentId=\"$deploymentId\"}",
     "legendFormat": "Job {{job_id}}"
    }
   ]
  },
  { "title": "JVM Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Flink Master Heap Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used{deploymentId=\"$deploymentId\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Taskmanager Heap Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used{deploymentId=\"$deploymentId\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}